version: '3'
services:
  web:
    build: ./docker/development
    container_name: web
    stdin_open: true
    tty: true
    command: "bash ./docker/development/entrypoint.sh"
    volumes:
      - .:/app
      - ./volumes/bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    # env_file:
    #   - web.env
  db:
    image: postgres:9.5.9
    # ports:
    #   - "5432:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
  redis:
    image: redis
    # ports:
    #   - "6379:6379"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080